GET https://aakarfoundry-backend.onrender.com/designs

###
POST https://aakarfoundry-backend.onrender.com/design/new
Content-Type: application/json

{
    "weight":"10",
    "casting": "abc",
    "area": "10",
    "dieCasting":"yes",
    "impressions": "abc",
    "rawMaterial": "abc",
    "dieCost": "aa",
    "coreCost": "aa",
    "dieLife": "aa",
    "diePeriod": "aa",
    "shots": "aa",
    "cores": "aa",
    "sandWeight":"aa",
    "remarks": "aa"
}