GET https://aakarfoundry-backend.onrender.com/registers

###
POST https://aakarfoundry-backend.onrender.com/register/new
Content-Type: application/json

{
        "name":"Vinayak Joshi",
        "email":"vinyak.joshi@aakarfoundry.com",
        "number":"9867543201",
        "department":"Marketing",
        "priority": "HOD"
}